### ISSUE TITLE
Fail to make on linux

### ISSUE THREAD

**Issue by sunrong0511** [open-license-manager/open-license-manager#104] opened 2020-08-11 11:05 UTC
![2020-08-11 19-03-24屏幕截图](https://user-images.githubusercontent.com/30221502/89890298-b05c2f00-dc05-11ea-88b4-6592a2f3de0e.png)

**Comment by sunrong0511** [comment] 2020-08-11 11:08
when i compile this project on a jetsonnano, it shows lacking file "cpuid.h".

**Comment by sunrong0511** [comment] 2020-08-12 01:00
Is there something wrong with my device,or where can i get the cupid.h ?

**Comment by gcontini** [comment] 2020-10-10 05:10
cpuid.h should come with the standard gcc headers. Are you building on ARM?

Please provide more details on your system.
see the build guide [here](http://open-license-manager.github.io/open-license-manager/development/Build-the-library.html)

**Comment by gcontini** [comment] 2020-11-04 14:45
no informations for long time most probably a duplicate of #83

**Closed by gcontini** 2020-11-04 14:45 UTC
Labels: undecided
